# Clean Conflicting Permission Files
# Removes auto-generated permission files that can conflict with main configuration

param(
    [string]$PowerPagesPath = "powerpages/rcsa-copilot---site-5joks"
)

Write-Host "🧹 CLEANING CONFLICTING PERMISSION FILES" -ForegroundColor Cyan
Write-Host "=========================================" -ForegroundColor Cyan

$cleanedFiles = @()
$errors = @()

# Define paths to check for conflicting files
$nestedTablePermPath = "$PowerPagesPath/rcsa-copilot---site-5joks/table-permissions"
$mainTablePermPath = "$PowerPagesPath/table-permissions"

# Ensure main permission file exists
$mainRiskCtrlPermission = "$mainTablePermPath/Web-API-RiskCtrl.tablepermission.yml"
if (-not (Test-Path $mainRiskCtrlPermission)) {
    $errors += "❌ CRITICAL: Main permission file missing: $mainRiskCtrlPermission"
    Write-Host "❌ Main permission file not found - cannot proceed safely" -ForegroundColor Red
    exit 1
}

Write-Host "✅ Main permission file confirmed: Web-API-RiskCtrl.tablepermission.yml" -ForegroundColor Green

# Clean nested directory conflicts
if (Test-Path $nestedTablePermPath) {
    Write-Host "`n🔍 Scanning nested directory for conflicts..." -ForegroundColor Yellow
    
    # Find all junction table permission files in nested directory
    $conflictingFiles = Get-ChildItem $nestedTablePermPath -Filter "*.yml" | Where-Object { 
        $_.Name -match "riskctrl|RiskCtrl|cr129_riskctrl" -and 
        $_.Name -ne "Web-API-RiskCtrl.tablepermission.yml"
    }
    
    if ($conflictingFiles.Count -gt 0) {
        Write-Host "🗑️ Found $($conflictingFiles.Count) conflicting files to remove:" -ForegroundColor Yellow
        
        foreach ($file in $conflictingFiles) {
            try {
                Write-Host "   Removing: $($file.Name)" -ForegroundColor Yellow
                Remove-Item $file.FullName -Force
                $cleanedFiles += $file.FullName
            }
            catch {
                $errors += "❌ Failed to remove: $($file.FullName) - $($_.Exception.Message)"
            }
        }
    } else {
        Write-Host "✅ No conflicting files found in nested directory" -ForegroundColor Green
    }
} else {
    Write-Host "✅ Nested directory doesn't exist - no conflicts possible" -ForegroundColor Green
}

# Clean any auto-generated permission files in main directory
Write-Host "`n🔍 Scanning main directory for auto-generated conflicts..." -ForegroundColor Yellow

$autoGeneratedFiles = Get-ChildItem $mainTablePermPath -Filter "*.yml" | Where-Object {
    ($_.Name -match "cr129_riskctrl_[a-f0-9]{8}" -or  # GUID-suffixed files
     $_.Name -match "RiskControl-Web-API" -or          # Alternative naming
     $_.Name -match "RiskCtrl---Web-API") -and         # Auto-generated naming
    $_.Name -ne "Web-API-RiskCtrl.tablepermission.yml"
}

if ($autoGeneratedFiles.Count -gt 0) {
    Write-Host "🗑️ Found $($autoGeneratedFiles.Count) auto-generated files to remove:" -ForegroundColor Yellow
    
    foreach ($file in $autoGeneratedFiles) {
        try {
            Write-Host "   Removing: $($file.Name)" -ForegroundColor Yellow
            Remove-Item $file.FullName -Force
            $cleanedFiles += $file.FullName
        }
        catch {
            $errors += "❌ Failed to remove: $($file.FullName) - $($_.Exception.Message)"
        }
    }
} else {
    Write-Host "✅ No auto-generated files found in main directory" -ForegroundColor Green
}

# Verify main permission file integrity
Write-Host "`n🔍 Verifying main permission file integrity..." -ForegroundColor Yellow

$content = Get-Content $mainRiskCtrlPermission -Raw
$requiredElements = @(
    'adx_enablewebapi:\s*true',
    'adx_entitylogicalname:\s*cr129_riskctrl',
    'adx_entityname:\s*Web-API-RiskCtrl'
)

$integrityIssues = @()
foreach ($element in $requiredElements) {
    if ($content -notmatch $element) {
        $integrityIssues += "Missing or incorrect: $element"
    }
}

if ($integrityIssues.Count -gt 0) {
    Write-Host "⚠️ WARNING: Main permission file integrity issues:" -ForegroundColor Yellow
    foreach ($issue in $integrityIssues) {
        Write-Host "   - $issue" -ForegroundColor Yellow
    }
    Write-Host "   Consider restoring from backup: archive/junction-table-working-backup/" -ForegroundColor Yellow
} else {
    Write-Host "✅ Main permission file integrity verified" -ForegroundColor Green
}

# Report results
Write-Host "`n📊 CLEANUP RESULTS" -ForegroundColor Cyan
Write-Host "==================" -ForegroundColor Cyan

if ($cleanedFiles.Count -gt 0) {
    Write-Host "🧹 Successfully cleaned $($cleanedFiles.Count) conflicting files:" -ForegroundColor Green
    foreach ($file in $cleanedFiles) {
        Write-Host "   ✅ $file" -ForegroundColor Green
    }
} else {
    Write-Host "✅ No conflicting files found - configuration is clean" -ForegroundColor Green
}

if ($errors.Count -gt 0) {
    Write-Host "`n❌ ERRORS ENCOUNTERED:" -ForegroundColor Red
    foreach ($errorMsg in $errors) {
        Write-Host $errorMsg -ForegroundColor Red
    }
    exit 1
}

Write-Host "`n🎯 READY FOR UPLOAD" -ForegroundColor Green
Write-Host "Configuration is clean and ready for pac paportal upload" -ForegroundColor Green
exit 0 